# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='mbly_ref.proto',
  package='mbly',
  serialized_pb='\n\x0embly_ref.proto\x12\x04mbly\"\x86\x01\n\x06Ref_pt\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08position\x18\x02 \x01(\x02\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12$\n\x08is_valid\x18\x04 \x01(\x0e\x32\x12.mbly.Ref_pt.Valid\"\x1f\n\x05Valid\x12\x0b\n\x07invalid\x10\x00\x12\t\n\x05valid\x10\x01\"\'\n\x07Ref_pts\x12\x1c\n\x06ref_pt\x18\x01 \x03(\x0b\x32\x0c.mbly.Ref_pt')



_REF_PT_VALID = descriptor.EnumDescriptor(
  name='Valid',
  full_name='mbly.Ref_pt.Valid',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='invalid', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='valid', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=128,
  serialized_end=159,
)


_REF_PT = descriptor.Descriptor(
  name='Ref_pt',
  full_name='mbly.Ref_pt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='mbly.Ref_pt.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='mbly.Ref_pt.position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='distance', full_name='mbly.Ref_pt.distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_valid', full_name='mbly.Ref_pt.is_valid', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REF_PT_VALID,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=159,
)


_REF_PTS = descriptor.Descriptor(
  name='Ref_pts',
  full_name='mbly.Ref_pts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ref_pt', full_name='mbly.Ref_pts.ref_pt', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=161,
  serialized_end=200,
)


_REF_PT.fields_by_name['is_valid'].enum_type = _REF_PT_VALID
_REF_PT_VALID.containing_type = _REF_PT;
_REF_PTS.fields_by_name['ref_pt'].message_type = _REF_PT

class Ref_pt(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REF_PT
  
  # @@protoc_insertion_point(class_scope:mbly.Ref_pt)

class Ref_pts(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REF_PTS
  
  # @@protoc_insertion_point(class_scope:mbly.Ref_pts)

# @@protoc_insertion_point(module_scope)
