# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mbly_ref.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mbly_ref.proto',
  package='mbly',
  serialized_pb=_b('\n\x0embly_ref.proto\x12\x04mbly\"\x86\x01\n\x06Ref_pt\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08position\x18\x02 \x01(\x02\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12$\n\x08is_valid\x18\x04 \x01(\x0e\x32\x12.mbly.Ref_pt.Valid\"\x1f\n\x05Valid\x12\x0b\n\x07invalid\x10\x00\x12\t\n\x05valid\x10\x01\"\'\n\x07Ref_pts\x12\x1c\n\x06ref_pt\x18\x01 \x03(\x0b\x32\x0c.mbly.Ref_pt')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REF_PT_VALID = _descriptor.EnumDescriptor(
  name='Valid',
  full_name='mbly.Ref_pt.Valid',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='valid', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=128,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_REF_PT_VALID)


_REF_PT = _descriptor.Descriptor(
  name='Ref_pt',
  full_name='mbly.Ref_pt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mbly.Ref_pt.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='mbly.Ref_pt.position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='mbly.Ref_pt.distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_valid', full_name='mbly.Ref_pt.is_valid', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REF_PT_VALID,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=159,
)


_REF_PTS = _descriptor.Descriptor(
  name='Ref_pts',
  full_name='mbly.Ref_pts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_pt', full_name='mbly.Ref_pts.ref_pt', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=200,
)

_REF_PT.fields_by_name['is_valid'].enum_type = _REF_PT_VALID
_REF_PT_VALID.containing_type = _REF_PT
_REF_PTS.fields_by_name['ref_pt'].message_type = _REF_PT
DESCRIPTOR.message_types_by_name['Ref_pt'] = _REF_PT
DESCRIPTOR.message_types_by_name['Ref_pts'] = _REF_PTS

Ref_pt = _reflection.GeneratedProtocolMessageType('Ref_pt', (_message.Message,), dict(
  DESCRIPTOR = _REF_PT,
  __module__ = 'mbly_ref_pb2'
  # @@protoc_insertion_point(class_scope:mbly.Ref_pt)
  ))
_sym_db.RegisterMessage(Ref_pt)

Ref_pts = _reflection.GeneratedProtocolMessageType('Ref_pts', (_message.Message,), dict(
  DESCRIPTOR = _REF_PTS,
  __module__ = 'mbly_ref_pb2'
  # @@protoc_insertion_point(class_scope:mbly.Ref_pts)
  ))
_sym_db.RegisterMessage(Ref_pts)


# @@protoc_insertion_point(module_scope)
